### ISSUE TITLE
Contributors section not working

### ISSUE THREAD

**Issue by jatinluthra14** [jboss-outreach/gci#65]
The contributors section is not loading.
Here is a screenshot of issue.
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/10234506/34357740-a6557a96-ea6f-11e7-9618-742f55a1fa87.PNG">

**Comment by SachinRammoorthy** [comment]
@jatinluthra14 You have to wait for ~5-6 seconds before it loads

If it still does not work, it is probably due to your remaining rate limit...check the `rate.remaining` property here: https://api.github.com/rate_limit . If it is 0, wait for an hour or so and try again when the remaining is greater than 0.

Hope this helps.

**Comment by jatinluthra14** [comment]
@SachinRammoorthy, Hi I know about rate limit and it is more that 0. Still not working

**Comment by SachinRammoorthy** [comment]
Works for me...
![screen shot 2017-12-26 at 7 49 28 pm](https://user-images.githubusercontent.com/20569603/34358454-eac335a0-ea75-11e7-9860-a222932c2985.png)

**Comment by jatinluthra14** [comment]
Wow. Let's see if it works after I try somethings. Till then I'll close the issue
